//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pan.kaikj.wxsupermarket.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mproduct
    {
        public string productid { get; set; }
        public int classid { get; set; }
        public string className { get; set; }
        public string supclassName { get; set; }
        public int supclassid { get; set; }
        public string productname { get; set; }
        public string productformat { get; set; }
        public string productformatunit { get; set; }
        public decimal origprice { get; set; }
        public decimal sellprice { get; set; }
        public int stock { get; set; }
        public int shelfstate { get; set; }
        public int hassellnum { get; set; }
        public string productdetails { get; set; }
        public string productimgurl { get; set; }
        public int priority { get; set; }
        public string isDelete { get; set; }
        public string isEffective { get; set; }
        public DateTime great_time { get; set; }
        public DateTime modify_time { get; set; }
        public int recommend { get; set; }
    }
}
