//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pan.kaikj.wxsupermarket.AdoModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mproductclass
    {
        public int classid { get; set; }
        public int supclassid { get; set; }
        public string classname { get; set; }
        public int priority { get; set; }
        public int isDelete { get; set; }
        public int isEffective { get; set; }
        public DateTime great_time { get; set; }
        public DateTime modify_time { get; set; }
        public string imgpath { get; set; }
    }
}
